
Describe 'Comment based help' {

    $HelpTestMod = New-Module -Name HelpTestMod -ScriptBlock {
        
        . "$PSScriptRoot\..\DatabaseReporter.ps1"
        
        DbReaderCommand HelpTest1 {
            <#
                .DESCRIPTION
                Overridden description
            #>
            [MagicDbInfo(
                FromClause = 'TableName',
                DbConnectionString = 'ConnectionString',
                DbConnectionType = 'System.Data.SqlClient.SqlConnection'
            )]
            param()
        }
        DbReaderCommand HelpTest2 {
            <#
                .SYNOPSIS
                Overridden synopsis
                .NOTES
                Some notes
                .EXAMPLE
                An example
                .EXAMPLE
                Another example
            #>
            [MagicDbInfo(
                FromClause = 'FromTable',
                DbConnectionString = 'ConnectionString',
                DbConnectionType = 'System.Data.SqlClient.SqlConnection'
            )]
            param()
        }
    }

    $HelpTest1Help = (Get-Command HelpTest1).ScriptBlock.Ast.GetHelpContent()
    $HelpTest2Help = (Get-Command HelpTest2).ScriptBlock.Ast.GetHelpContent()

    It 'Properly merges help content' {
        $HelpTest1Help.Synopsis | ForEach-Object Trim | Should Be 'A dynamic command generated by the DatabaseReporter framework.'
        $HelpTest1Help.Description | ForEach-Object Trim | Should Be 'Overridden description'
        $HelpTest1Help.examples[0] | ForEach-Object Trim |  Should Be ('PS> Verb-Noun -GroupBy ParameterName

Explain generic example #1 here' -replace '\r')
        $HelpTest1Help.examples.Count | Should Be 2
        $HelpTest2Help.Synopsis | ForEach-Object Trim | Should Be 'Overridden synopsis'
        $HelpTest2Help.Description | ForEach-Object Trim | Should Be ('This is a command that was generated by the DatabaseReporter framework.

While no command-specific help was specified, some more generic help would be
very helpful here :)' -replace '\r')
        $HelpTest2Help.Notes | ForEach-Object Trim | Should Be 'Some notes'
        $HelpTest2Help.examples[0] | ForEach-Object Trim |  Should Be 'An example'
        $HelpTest2Help.examples[1] | ForEach-Object Trim |  Should Be 'Another example'
        $HelpTest2Help.examples.Count | Should Be 2
    }
}